"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = [
    'name',
    'description',
    'version',
    'private',
    'author',
    'contributors',
    'funding',
    'license',
    'main',
    'module',
    'jsnext:main',
    'files',
    'preferGlobal',
    'bin',
    'scripts',
    'homepage',
    'repository',
    'bugs',
    'keywords',
    'dependencies',
    'devDependencies',
];
